import { PHASES, attack, advancePlayerPhase, chargeAndDraw, createMatch, playCard, playOpponentTurn } from './engine.js';

let match = createMatch();
let selected = null;
let opponentIsPlaying = false;
const $ = selector => document.querySelector(selector);

function notify(message) { $('#toast').textContent = message; $('#toast').hidden = false; window.setTimeout(() => { $('#toast').hidden = true; }, 2600); }
function cardMarkup(card, inField = false) { return `<button class="card ${card.type} ${card.rest ? 'rest' : ''} ${inField ? 'field-card' : ''}"><span class="card-top"><small>${card.world}</small><b>${card.size ? `T${card.size}` : ''}</b></span><strong class="card-name">${card.name}</strong><span class="card-type">${card.type.toUpperCase()}</span><span class="card-stats">${card.power ? `${card.power} / CRIT ${card.crit}` : ''}</span><small class="card-text">${card.text}</small></button>`; }
function renderZones() { document.querySelectorAll('.zone').forEach(zone => { const card = match[zone.dataset.owner].field[zone.dataset.zone]; zone.innerHTML = card ? cardMarkup(card, true) : `<span>${zone.dataset.zone === 'item' ? 'Ítem' : zone.dataset.zone[0].toUpperCase() + zone.dataset.zone.slice(1)}</span>`; if (card && zone.dataset.owner === 'player' && match.phase === 4 && !card.rest && zone.dataset.zone !== 'item') zone.querySelector('button').onclick = () => { const result = attack(match, 'player', zone.dataset.zone); if (!result.ok) notify(result.reason); render(); }; }); }
function renderHand() { $('#hand').innerHTML = match.player.hand.map((card, index) => cardMarkup(card).replace('class="card', `class="card ${selected === index ? 'selected' : ''}`)).join(''); [...$('#hand').children].forEach((card, index) => { card.onclick = () => { selected = index; render(); }; }); $('#selection-text').textContent = selected === null ? 'Selecciona una carta' : match.player.hand[selected].name; }
function renderGauge(who) { $(`#${who}-gauge`).innerHTML = match[who].gauge.map(() => '<i class="filled"></i>').join('') || '<i></i><i></i><i></i>'; }
function render() { const { player, opponent } = match; $('#phase-name').textContent = opponentIsPlaying ? 'Turno rival' : match.phase < 0 ? 'Preparación' : PHASES[match.phase]; $('#turn-name').textContent = opponentIsPlaying ? 'Nova está jugando' : 'Turno de Kai'; $('#round').textContent = match.round; [['player', player], ['opponent', opponent]].forEach(([key, fighter]) => { $(`#${key}-life`).textContent = fighter.life; $(`#${key}-deck`).textContent = fighter.deck.length; $(`#${key}-hand-count`).textContent = fighter.hand.length; renderGauge(key); }); renderZones(); renderHand(); $('#game-log').innerHTML = match.log.map(entry => `<li>${entry}</li>`).join(''); $('#action-title').textContent = opponentIsPlaying ? 'Turno de Nova' : match.finished ? 'Lucha terminada' : match.phase < 0 ? 'Empieza tu turno' : `${PHASES[match.phase]} de Kai`; $('#action-hint').textContent = opponentIsPlaying ? 'Espera a que Nova termine.' : 'Elige una carta y usa las acciones disponibles en cada fase.'; $('#charge').disabled = opponentIsPlaying || match.phase !== 2 || selected === null || match.finished; $('#play').disabled = opponentIsPlaying || match.phase !== 3 || selected === null || match.finished; $('#next-phase').disabled = opponentIsPlaying || match.finished; }
function nextPhase() { const result = advancePlayerPhase(match); if (!result.ok) { if (match.phase === PHASES.length - 1 && !match.finished) { opponentIsPlaying = true; render(); window.setTimeout(() => { playOpponentTurn(match); opponentIsPlaying = false; selected = null; render(); }, 650); } else notify(result.reason); return; } render(); }
function useAction(action) { if (selected === null) return; const result = action(match, selected); if (!result.ok) { notify(result.reason); return; } selected = null; render(); }
$('#next-phase').onclick = nextPhase; $('#restart').onclick = () => { match = createMatch(); selected = null; opponentIsPlaying = false; render(); }; $('#charge').onclick = () => useAction(chargeAndDraw); $('#play').onclick = () => useAction(playCard); render();
